services:
  postgres:
    image: postgres:16-alpine
    container_name: gamemod-postgres
    environment:
      POSTGRES_DB: gamemod
      POSTGRES_USER: gamemod
      POSTGRES_PASSWORD: gamemod
    ports:
      - "5544:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gamemod -d gamemod"]
      interval: 10s
      timeout: 5s
      retries: 5
